spring.application.name=sms-service
server.port=8083
# Si tu ajoutes la sécurité plus tard :
# spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/auth/realms/Orange-Realm
# Configuration Swagger
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
# Pour scanner uniquement tes contrôleurs
springdoc.packages-to-scan=tn.esprit.smsservice.Controller
logging.level.tn.esprit.smsservice=DEBUG

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration