server.port=8089
cxf.path=/services

jbpm.server.url=http://localhost:8080/kie-server/services/rest/server
jbpm.server.user=wbadmin
jbpm.server.password=wbadmin

jbpm.container.id=portabilityin_1.0.0-SNAPSHOT
jbpm.process.in.id=portabilitefinal.Portabilite_Orchestration


jbpm.container.out.id=portaout_1.0.0-SNAPSHOT
jbpm.process.out.id=portaout.portaout

monitoring.load-variables=true
monitoring.load-variables-only-active=false



