spring.application.name=crm-module
server.port=8086
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [Correlation-ID: %X{correlationId}] - %msg%n
# Indique à Spring où se trouve ton serveur Keycloak pour vérifier les jetons
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/auth/realms/Orange-Realm
spring.jackson.serialization.write-dates-as-timestamps=false


Configuration KIE Server - Désactiver le scan de classes problématiques
kie.server.classloader.scanning=false
kie.server.scanning.excluded-packages=org.jbpm.osgi,org.joda.time,org.mozilla.javascript,xom