spring.application.name=monitoring-back

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/monitoring_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Port API pour React
server.port=8081

# jBPM / KIE Server
jbpm.server.url=http://localhost:8080/kie-server/services/rest/server
jbpm.server.user=wbadmin
jbpm.server.password=wbadmin


ai.enabled=true
ai.python.service-url=http://localhost:5001

# SMS (simulation par défaut pour dev)
# sms.simulate=false + SendGrid configuré = vrai envoi email-to-SMS via opérateur
sms.simulate=true

# SMTP Gmail pour email-to-SMS via opérateur
# Remplacer par un vrai compte Gmail + mot de passe d'application
sms.email.from=toncompte@gmail.com
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=toncompte@gmail.com
spring.mail.password=TON_MDP_APPLICATION_16_LETTRES
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true





