spring.application.name=bscs-module
server.port=8085

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [Correlation-ID: %X{correlationId}] - %msg%n
# Indique à Spring où se trouve ton serveur Keycloak pour vérifier les jetons
//spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/auth/realms/Orange-Realm 

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.tn.esprit.bscsmodule=TRACE