spring.application.name=npservice-module
server.port=8084
jbpm.container.id=porta_1.0.0-SNAPSHOT

spring.main.allow-bean-definition-overriding=true
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - [Correlation-ID: %X{correlationId}] - %msg%n
# Indique à Spring où se trouve ton serveur Keycloak pour vérifier les jetons
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/auth/realms/Orange-Realm